apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-sandbox
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-sandbox
  template:
    metadata:
      labels:
        app: dev-sandbox
    spec:
      containers:
        - name: dev-sandbox-container
          image: dev-sandbox-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
